In [27]:
import torch
import torch.nn as nn

kernel_size = 10
stride=5
padding=3
output_padding=0

dconv1 = nn.ConvTranspose1d(1, 1, kernel_size=kernel_size, stride=stride, padding=padding, output_padding=output_padding, bias=False)
dconv1.weight.data = torch.ones(1,1,kernel_size)
print('=====dconv1=====')
for name, l in dconv1.named_parameters():
    print('{}={}'.format(name, l.data))

# B, C, T
x = torch.ones(1, 1, 1)
# To = Ti * kernel_size - 2*padding + output_padding
print(x.numel()*kernel_size - 2*padding + output_padding)
x3 = dconv1(x)
print('=====dconv1 out=====')
print(x3)
print(x3.numel())

print('===================')




k = 10
stride=5
padding=3
output_padding=1


dconv1 = nn.ConvTranspose1d(1, 1, kernel_size=k, stride=stride, padding=padding, output_padding=output_padding, bias=False)
dconv1.weight.data = torch.ones(1,1,k)
print('=====dconv1=====')
for name, l in dconv1.named_parameters():
    print('{}={}'.format(name, l.data))

    
# B, C, T
x = torch.ones(1, 1, 1)
# To = Ti * k - 2*padding + output_padding
print(x.numel()*k - 2*padding + output_padding)
x3 = dconv1(x)
print('=====dconv1 out=====')
print(x3)
print(x3.numel())

print('===================')




k = 10
stride=5
padding=0
output_padding=1

dconv1 = nn.ConvTranspose1d(1, 1, kernel_size=k, stride=stride, padding=padding, output_padding=output_padding, bias=False)
dconv1.weight.data = torch.ones(1,1,k)
print('=====dconv1=====')
for name, l in dconv1.named_parameters():
    print('{}={}'.format(name, l.data))
    
# B, C, T
x = torch.ones(1, 1, 1)
# To = Ti * k - 2*padding + output_padding
print(x.numel()*k - 2*padding + output_padding)
x3 = dconv1(x)
print('=====dconv1 out=====')
print(x3)
print(x3.numel())


print('===================')




k = 10
stride=5
padding=1
output_padding=1

dconv1 = nn.ConvTranspose1d(1, 1, kernel_size=k, stride=stride, padding=padding, output_padding=output_padding, bias=False)
dconv1.weight.data = torch.ones(1,1,k)
print('=====dconv1=====')
for name, l in dconv1.named_parameters():
    print('{}={}'.format(name, l.data))
    
# B, C, T
x = torch.ones(1, 1, 1)
# To = Ti * k - 2*padding + output_padding
print(x.numel()*k - 2*padding + output_padding)
x3 = dconv1(x)
print('=====dconv1 out=====')
print(x3)
print(x3.numel())

=====dconv1=====
weight=tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
4
=====dconv1 out=====
tensor([[[1., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)
4
=====dconv1=====
weight=tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
5
=====dconv1 out=====
tensor([[[1., 1., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)
5
=====dconv1=====
weight=tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
11
=====dconv1 out=====
tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]]],
       grad_fn=<SqueezeBackward1>)
11
=====dconv1=====
weight=tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
9
=====dconv1 out=====
tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)
9


In [44]:
import torch
import torch.nn as nn

k = 10
stride=5
padding=3
output_padding=1
dilation=1


dconv1 = nn.ConvTranspose1d(1, 1, kernel_size=k, stride=stride, padding=padding, output_padding=output_padding, dilation=dilation, bias=False)

dconv1.weight.data = torch.ones(1,1,k)

print('=====dconv1=====')
for name, l in dconv1.named_parameters():
    print('{}={}'.format(name, l.data))

    
# B, C, T
x = torch.ones(1, 1, 1)
# To = Ti * k - 2*padding + output_padding
print(x.numel()*k - 2*padding + output_padding)
x3 = dconv1(x)
print('=====dconv1 out=====')
print(x3)



# B, C, T
x = torch.ones(1, 1, 2)
print(x.numel())
# To = Ti * k - 2*padding + output_padding
print('To', (x.numel() - 1)* stride + dilation*(k-1) + 1 + output_padding - 2*padding)
x3 = dconv1(x)
print('=====dconv1 out=====')
print(x3)
print(x3.numel())

print('Ti', (x3.numel() + 2*padding - output_padding - 1 - dilation * (k-1) )/stride + 1)

=====dconv1=====
weight=tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
5
=====dconv1 out=====
tensor([[[1., 1., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)
2
To 10
=====dconv1 out=====
tensor([[[1., 1., 2., 2., 2., 2., 2., 1., 1., 1.]]],
       grad_fn=<SqueezeBackward1>)
10
Ti 2.0
