In [6]:
import torch
import torch.nn.functional as F

In [3]:
logits = torch.randn(32, 10, 256)
print(logits.shape)

torch.Size([32, 10, 256])


In [11]:
# softmax is not idempotent
probs = F.softmax(logits)
print(probs[0])
pprobs = F.softmax(probs)
print(pprobs[0])

tensor([[0.0105, 0.0608, 0.0083,  ..., 0.0298, 0.0133, 0.0032],
        [0.0198, 0.0111, 0.0299,  ..., 0.0073, 0.0037, 0.0440],
        [0.0581, 0.0069, 0.0040,  ..., 0.0085, 0.0251, 0.0063],
        ...,
        [0.0105, 0.0086, 0.0104,  ..., 0.0700, 0.0613, 0.0137],
        [0.0648, 0.0134, 0.0228,  ..., 0.1732, 0.0334, 0.0051],
        [0.0109, 0.0867, 0.0148,  ..., 0.0053, 0.0125, 0.0358]])
tensor([[0.0306, 0.0322, 0.0305,  ..., 0.0312, 0.0307, 0.0303],
        [0.0309, 0.0306, 0.0312,  ..., 0.0305, 0.0304, 0.0316],
        [0.0321, 0.0305, 0.0304,  ..., 0.0305, 0.0310, 0.0305],
        ...,
        [0.0306, 0.0305, 0.0306,  ..., 0.0325, 0.0322, 0.0307],
        [0.0323, 0.0307, 0.0310,  ..., 0.0360, 0.0313, 0.0304],
        [0.0306, 0.0330, 0.0307,  ..., 0.0304, 0.0306, 0.0314]])


/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.
/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  This is separate from the ipykernel package so we can avoid doing imports until


In [16]:
# log_softmax is not idempotent
logprob=F.log_softmax(logits)
print(logprob[0])
loglogprob=F.log_softmax(logprob)
print(loglogprob[0])

tensor([[-4.5583, -2.7997, -4.7860,  ..., -3.5130, -4.3199, -5.7474],
        [-3.9224, -4.5015, -3.5100,  ..., -4.9203, -5.6071, -3.1234],
        [-2.8464, -4.9733, -5.5309,  ..., -4.7703, -3.6835, -5.0669],
        ...,
        [-4.5568, -4.7574, -4.5682,  ..., -2.6587, -2.7915, -4.2939],
        [-2.7360, -4.3161, -3.7797,  ..., -1.7531, -3.3978, -5.2746],
        [-4.5224, -2.4449, -4.2109,  ..., -5.2330, -4.3797, -3.3299]])
tensor([[-4.5583, -2.7997, -4.7860,  ..., -3.5130, -4.3199, -5.7474],
        [-3.9224, -4.5015, -3.5100,  ..., -4.9203, -5.6071, -3.1234],
        [-2.8464, -4.9733, -5.5309,  ..., -4.7703, -3.6835, -5.0669],
        ...,
        [-4.5568, -4.7574, -4.5682,  ..., -2.6587, -2.7915, -4.2939],
        [-2.7360, -4.3161, -3.7797,  ..., -1.7531, -3.3978, -5.2746],
        [-4.5224, -2.4449, -4.2109,  ..., -5.2330, -4.3797, -3.3299]])


/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  
/workspace/DeepSpeech-2.x/tools/venv/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  after removing the cwd from sys.path.
